import { SlashCommandBuilder, EmbedBuilder, AttachmentBuilder, ChannelType, PermissionFlagsBits } from 'discord.js';

export default {
  data: new SlashCommandBuilder()
    .setName('transcript')
    .setDescription('Generate a transcript of the current ticket')
    .addChannelOption(option =>
      option
        .setName('channel')
        .setDescription('Channel to send the transcript to')
        .addChannelTypes(ChannelType.GuildText)
        .setRequired(true)
    )
    .setDefaultMemberPermissions(PermissionFlagsBits.ManageChannels),

  async execute(interaction) {
    try {
      await interaction.deferReply({ ephemeral: true });

      const targetChannel = interaction.options.getChannel('channel');
      const currentChannel = interaction.channel;

      // Check if this is a ticket channel
      if (!currentChannel.name.startsWith('ticket-') && !currentChannel.name.startsWith('claimed-ticket-')) {
        return await interaction.editReply({
          content: '❌ This command can only be used in ticket channels!'
        });
      }

      // Generate ticket number from channel name or random
      let ticketNumber = Math.floor(Math.random() * 10000);
      
      // Try to extract ticket number from channel topic if it exists
      if (currentChannel.topic && currentChannel.topic.includes('Ticket #')) {
        const match = currentChannel.topic.match(/Ticket #(\d+)/);
        if (match) {
          ticketNumber = parseInt(match[1]);
        }
      }

      // Fetch messages from the ticket channel
      const messages = await currentChannel.messages.fetch({ limit: 100 });
      const sortedMessages = messages.sort((a, b) => a.createdTimestamp - b.createdTimestamp);

      // Generate transcript content
      let transcriptContent = `TICKET TRANSCRIPT #${ticketNumber}\n`;
      transcriptContent += `Channel: ${currentChannel.name}\n`;
      transcriptContent += `Created: ${currentChannel.createdAt.toLocaleString()}\n`;
      transcriptContent += `Generated: ${new Date().toLocaleString()}\n`;
      transcriptContent += `Generated by: ${interaction.user.tag}\n`;
      transcriptContent += `${'='.repeat(50)}\n\n`;

      for (const message of sortedMessages.values()) {
        const timestamp = message.createdAt.toLocaleString();
        const author = message.author.tag;
        const content = message.content || '[No text content]';
        
        transcriptContent += `[${timestamp}] ${author}: ${content}\n`;
        
        // Add attachment info
        if (message.attachments.size > 0) {
          message.attachments.forEach(attachment => {
            transcriptContent += `    📎 Attachment: ${attachment.name} (${attachment.url})\n`;
          });
        }
        
        // Add embed info
        if (message.embeds.length > 0) {
          transcriptContent += `    📋 Embed: ${message.embeds[0].title || 'Untitled'}\n`;
        }
        
        transcriptContent += '\n';
      }

      // Create transcript file
      const transcriptBuffer = Buffer.from(transcriptContent, 'utf-8');
      const transcriptAttachment = new AttachmentBuilder(transcriptBuffer, { 
        name: `ticket-${ticketNumber}-transcript.txt` 
      });

      // Create transcript embed
      const transcriptEmbed = new EmbedBuilder()
        .setColor('#2196F3')
        .setTitle(`📄 Ticket Transcript #${ticketNumber}`)
        .setDescription(`Transcript generated for ticket: **${currentChannel.name}**`)
        .addFields(
          { name: '🎫 Ticket Channel', value: currentChannel.toString(), inline: true },
          { name: '📊 Total Messages', value: sortedMessages.size.toString(), inline: true },
          { name: '👤 Generated By', value: interaction.user.toString(), inline: true },
          { name: '📅 Created', value: `<t:${Math.floor(currentChannel.createdTimestamp / 1000)}:F>`, inline: true },
          { name: '📅 Generated', value: `<t:${Math.floor(Date.now() / 1000)}:F>`, inline: true }
        )
        .setFooter({ text: `Ticket #${ticketNumber}` })
        .setTimestamp();

      // Send transcript to target channel
      await targetChannel.send({
        embeds: [transcriptEmbed],
        files: [transcriptAttachment]
      });

      await interaction.editReply({
        content: `✅ Transcript generated successfully and sent to ${targetChannel}!`
      });

    } catch (error) {
      console.error('Transcript command error:', error);
      await interaction.editReply({
        content: '❌ Failed to generate transcript. Please try again!'
      });
    }
  },
};